FROM python:3.6-slim-jessie

COPY ./core /app/core

EXPOSE 3001

WORKDIR /app/core

RUN apt-get update && \
apt-get install -y --no-install-recommends tzdata && rm -rf /var/lib/apt/lists/* && \
pip3 install -r requirements.txt

