FROM node

WORKDIR /app

RUN npm install -g forever

COPY ./serve/package.json /app/

RUN npm install

# Install Python.
RUN \
apt-get update && \
apt-get install -y python python-dev python-pip python-virtualenv python3 python3-dev python3-pip python3-virtualenv && \
rm -rf /var/lib/apt/lists/*

COPY . /app/

EXPOSE 3000

RUN cd /app/serve

CMD forever bin/www  
