FROM debian:jessie

ENV TZ Asia/Shanghai

WORKDIR /app

# Install Python.
RUN \
apt-get update && \
apt-get install --fix-missing -y python python-dev python-pip python-virtualenv python3 python3-dev python3-pip python3-virtualenv libxml2-dev libxslt-dev && \
apt-get update && apt-get install -y --no-install-recommends tzdata && \
rm -rf /var/lib/apt/lists/*

COPY ./core /app/core

EXPOSE 3001

WORKDIR /app/core

RUN \
pip3 install -r requirements.txt

