FROM node:10.15

ENV LANG C.UTF-8

COPY . /app

WORKDIR /app/serve

RUN npm install

WORKDIR /app/core

# Install Python.
RUN \
apt-get update && \
apt-get install --fix-missing -y python python-dev python-pip python-virtualenv python3 python3-dev python3-pip python3-virtualenv && \
rm -rf /var/lib/apt/lists/*

RUN pip3 install -r requirements.txt

EXPOSE 3000

WORKDIR /app/serve/

CMD npm run dev  