FROM node

WORKDIR /app

ENV LANG C.UTF-8

COPY ./serve/package.json /app/

RUN npm install

# Install Python.
RUN \
apt-get update && \
apt-get install -y python python-dev python-pip python-virtualenv python3 python3-dev python3-pip python3-virtualenv && \
rm -rf /var/lib/apt/lists/*

COPY . /app

EXPOSE 3000

WORKDIR /app/core

RUN \
pip3 install -r requirements.txt


# RUN cd /app/serve/
WORKDIR /app/serve/

CMD node bin/www  
