FROM node:10.15

ENV LANG C.UTF-8

COPY . /app

WORKDIR /app/serve

EXPOSE 3000

RUN npm  --registry https://registry.npm.taobao.org install -g pm2 && \
npm  --registry https://registry.npm.taobao.org install && \
npm audit fix

WORKDIR /app/core

#Install Python.

RUN apt-get update -y && \
apt-get install -y --no-install-recommends tzdata && \
apt-get install --fix-missing -y python python-dev python-pip python-virtualenv python3 python3-dev python3-pip python3-virtualenv && \
rm -rf /var/lib/apt/lists/* && \
pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple/ -r requirements.txt

WORKDIR /app/serve/

CMD npm run stage
#CMD npm run dev