#指定基于的基础镜像 (https://hub.docker.com/_/python/) 
FROM python:3
 
# Install Python Setuptools
RUN apt-get install -y python-setuptools

# Install pip
RUN easy_install pip

# Add and install Python modules
ADD requirements.txt /src/requirements.txt
RUN cd /src; pip install -r requirements.txt

# Bundle app source
ADD . /src

# Expose
EXPOSE 5000
  
# Run
CMD ["python", "/src/crawler.py"]
